-- Ensure the UUID extension is available
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Delete existing data for a clean slate
DELETE FROM public.study_logs;
DELETE FROM public.daily_plans;
DELETE FROM public.study_topics;
DELETE FROM public.subjects;
DELETE FROM public.feedback;
DELETE FROM public.suggestions;
DELETE FROM public.users;
DELETE FROM auth.users WHERE email = 'student@seed.com';

DO $$
DECLARE
  student_id UUID := '11111111-1111-1111-1111-111111111111';
  subject1_id UUID := uuid_generate_v4();
  subject2_id UUID := uuid_generate_v4();
  topic1_id UUID := uuid_generate_v4();
  topic2_id UUID := uuid_generate_v4();
  plan1_id UUID := uuid_generate_v4();
  plan2_id UUID := uuid_generate_v4();
  log1_id UUID := uuid_generate_v4();
BEGIN
  -- 1. Insert into auth.users (This will trigger public.users creation via your trigger)
  INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, 
    email_confirmed_at, recovery_sent_at, last_sign_in_at, 
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at
  )
  VALUES (
    '00000000-0000-0000-0000-000000000000',
    student_id,
    'authenticated',
    'authenticated',
    'student@seed.com',
    crypt('password123', gen_salt('bf')),
    current_timestamp,
    current_timestamp,
    current_timestamp,
    '{"provider":"email","providers":["email"]}',
    '{"name": "Seed Student"}',
    current_timestamp,
    current_timestamp
  );

  -- 1.5 Update public.users generated by the trigger
  UPDATE public.users 
  SET exam_type = 'JEE', preferred_time = 'Morning'
  WHERE id = student_id;

  -- 2. Insert Subjects
  INSERT INTO public.subjects (id, user_id, subject_name, category)
  VALUES 
    (subject1_id, student_id, 'Physics Engine Mechanics', 'Physics'),
    (subject2_id, student_id, 'Organic Chemistry', 'Chemistry');

  -- 3. Insert Topics
  INSERT INTO public.study_topics (id, subject_id, topic_name, complexity)
  VALUES 
    (topic1_id, subject1_id, 'Newton''s Laws', 'Medium'),
    (topic2_id, subject2_id, 'Hydrocarbons', 'Hard');

  -- 4. Insert Daily Plans for today
  INSERT INTO public.daily_plans (id, user_id, topic_id, target_duration, time_slot, plan_date)
  VALUES 
    (plan1_id, student_id, topic1_id, 120, 'Morning', CURRENT_DATE),
    (plan2_id, student_id, topic2_id, 90, 'Afternoon', CURRENT_DATE);

  -- 5. Insert Study Logs (one completed, one pending)
  INSERT INTO public.study_logs (id, plan_id, user_id, start_time, end_time, focus_level, distractions, reflection, fatigue_level, efficiency, throughput, quality_score)
  VALUES 
    (log1_id, plan1_id, student_id, NOW() - INTERVAL '2 hours', NOW(), 4, 'NONE', 'Understood the concepts well.', 2, 85.5, 90.0, 8.5);

  -- 6. Insert AI Suggestions
  INSERT INTO public.suggestions (user_id, log_id, suggestion_text, suggestion_type)
  VALUES 
    (student_id, log1_id, 'Great focus on Newton''s Laws! Consider taking a short 10m break before chemistry.', 'planning');
END $$;
