'use client'

import Link from 'next/link'
import { SparklesIcon } from '@/components/ui/AppIcons'

export default function HowItWorksPage() {
  return (
    <div className="landing-root">
      {/* Nav */}
      <nav className="landing-nav">
        <Link href="/" className="landing-logo" style={{ textDecoration: 'none' }}>OptiLearn</Link>
        <div className="landing-nav-links">
          <Link href="/features" style={{ fontSize: 14, fontWeight: 500, color: 'var(--text-mid)', textDecoration: 'none', transition: 'color .2s' }}>Features</Link>
          <Link href="/how-it-works" style={{ fontSize: 14, fontWeight: 600, color: 'var(--terra)', textDecoration: 'none' }}>How it Works</Link>
          <Link href="/about" style={{ fontSize: 14, fontWeight: 500, color: 'var(--text-mid)', textDecoration: 'none', transition: 'color .2s' }}>About</Link>
        </div>
        <div className="landing-nav-cta">
          <Link href="/login" className="btn-secondary btn-sm">Log in</Link>
          <Link href="/login" className="btn-primary btn-sm">Get Started Free →</Link>
        </div>
      </nav>

      {/* Hero */}
      <div className="landing-hero" style={{ flexDirection: 'column', textAlign: 'center', gap: 24, paddingBottom: 80, alignItems: 'center' }}>
        <div style={{ animation: 'slideUp .55s cubic-bezier(.22,.68,0,1.1) both', display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          <div className="hero-eyebrow"><SparklesIcon width={14} height={14} />From Planning to Insight</div>
          <div className="hero-title" style={{ maxWidth: 800 }}>How <em>OptiLearn</em> works.</div>
          <p style={{ fontSize: '16.5px', color: 'var(--text-mid)', lineHeight: 1.7, maxWidth: 640, margin: '24px auto 42px' }}>
            A closed-loop adaptive system — every action you take feeds back into smarter recommendations. Here&apos;s the six-step cycle that powers your academic growth.
          </p>
        </div>
        
        <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: 32, width: '100%', maxWidth: 800, animation: 'fadeIn .7s .25s both', textAlign: 'left' }}>
          {[
            {
              step: '1',
              title: 'Check In — Know Your Readiness',
              desc: 'Each day starts with a wellness check-in capturing sleep hours, sleep quality, energy, stress, mood, exercise, meals, and screen time. These 8 signals produce a weighted Readiness Score (0–100) that tells you — and the AI — how prepared you are today.'
            },
            {
              step: '2',
              title: 'Plan — Build Your Study Schedule',
              desc: 'Create study plans with subjects, topics, timeslots (Morning / Afternoon / Evening / Night), target durations, and difficulty tags. The database enforces logical time ordering and the planner color-codes entries by subject for a clear visual timeline.'
            },
            {
              step: '3',
              title: 'Execute & Log — Capture What Really Happened',
              desc: 'After each session, log your actual start/end time, rate focus (1–5) and fatigue (1–5), select distraction types (Phone, Noise, Social Media, etc.), and add a reflection. The system validates no overlaps and no future times, then auto-triggers the AI engine.'
            },
            {
              step: '4',
              title: 'Analyze — 8-Pattern Cognitive Pipeline',
              desc: 'Your logs pass through a 4-node LangGraph pipeline: Validate → Build Context → Generate → Parse. Before the LLM sees anything, a ContextBuilder computes 8 cross-dimensional patterns — planning accuracy, subject×timeslot efficiency, distraction triggers, fatigue curves, deep work ratio, best/worst combos, and completion rate — ensuring insight specificity.'
            },
            {
              step: '5',
              title: 'Act — Turn Insights into Plans',
              desc: 'AI recommendations are generated by Groq LLaMA 3.3 70B with a strict anti-rephrase contract: every insight must cite a number from your data. When an insight includes a plan suggestion, click "Add to Plan" to create a real study schedule entry — closing the full loop from analysis to action.'
            },
            {
              step: '6',
              title: 'Monitor — Track Progress & Prevent Burnout',
              desc: 'The analytics dashboard visualizes your story: Planned vs Actual charts, Activity Heatmaps, Subject Priority Matrix, and Efficiency by Weekday. A Burnout Monitor blends fatigue, consistency, and focus into a risk score. A Procrastination Tracker auto-detects skipped sessions. And a Weekly Digest gives you 3 Wins, 3 Issues, and 3 Actions — exportable as a PDF.'
            },
          ].map((item) => (
            <div key={item.title} className="card-flat" style={{ padding: '28px 32px', display: 'flex', gap: 24, alignItems: 'center', position: 'relative', overflow: 'hidden' }}>
              <div style={{ position: 'absolute', top: -10, left: -10, fontSize: 120, fontWeight: 900, color: 'var(--terra)', opacity: 0.05, lineHeight: 1, fontFamily: "'Plus Jakarta Sans', sans-serif" }}>
                {item.step}
              </div>
              <div style={{ width: 48, height: 48, borderRadius: '50%', background: 'linear-gradient(135deg, var(--terra) 0%, #D37339 100%)', color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20, fontWeight: 800, flexShrink: 0, zIndex: 1, boxShadow: 'var(--shadow-terra)' }}>
                {item.step}
              </div>
              <div style={{ zIndex: 1, flex: 1 }}>
                <div style={{ fontSize: 18, fontWeight: 800, fontFamily: "'Plus Jakarta Sans', sans-serif", marginBottom: 6, color: 'var(--text-dark)' }}>
                  {item.title}
                </div>
                <div style={{ fontSize: 14, color: 'var(--text-soft)', lineHeight: 1.6 }}>
                  {item.desc}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Pipeline visual */}
        <div className="card-flat" style={{ maxWidth: 800, width: '100%', padding: '24px 32px', marginTop: 8, animation: 'fadeIn .8s .4s both', textAlign: 'center' }}>
          <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '1.5px', textTransform: 'uppercase', color: 'var(--text-soft)', marginBottom: 16 }}>
            AI Engine Pipeline
          </div>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, flexWrap: 'wrap' }}>
            {[
              { label: 'Validate', emoji: '📝' },
              { label: 'Build Context', emoji: '🔍' },
              { label: 'Generate (LLM)', emoji: '🤖' },
              { label: 'Parse & Rank', emoji: '📊' },
            ].map((node, i) => (
              <div key={node.label} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                <div style={{
                  background: 'linear-gradient(135deg, #3D4F8C, #243070)',
                  color: 'white',
                  borderRadius: 12,
                  padding: '10px 16px',
                  fontSize: 13,
                  fontWeight: 700,
                  whiteSpace: 'nowrap',
                }}>
                  {node.emoji} {node.label}
                </div>
                {i < 3 && (
                  <span style={{ fontSize: 18, color: 'var(--terra)', fontWeight: 700 }}>→</span>
                )}
              </div>
            ))}
          </div>
          <div style={{ fontSize: 12, color: 'var(--text-soft)', marginTop: 12, lineHeight: 1.5 }}>
            8 cross-dimensional patterns computed before inference · LLaMA 3.3 70B via Groq · Evidence-cited output only
          </div>
        </div>
        
        <div style={{ marginTop: 20, animation: 'fadeIn .8s .45s both' }}>
          <Link href="/login" className="btn-primary" style={{ padding: '14px 32px', fontSize: 15 }}>Start the cycle today →</Link>
        </div>
      </div>
    </div>
  )
}
